import dotenv from "dotenv";
import bcrypt from "bcryptjs";
import { connectDB } from "./config/db.js";
import Category from "./models/Category.js";
import Product from "./models/Product.js";
import User from "./models/User.js";
dotenv.config();+
await connectDB();
const categories = [
  [
    "Electronics",
    "Phones, laptops and smart gadgets",
    "/src/assets/images/electronics.jpg",
  ],
  [
    "Fashion",
    "Clothing and everyday style",
    "/src/assets/images/fashion.jpg",
  ],
  [
    "Footwear",
    "Shoes for every occasion",
    "/src/assets/images/footwear.jpg",
  ],
  [
    "Accessories",
    "Watches and useful accessories",
    "/src/assets/images/accessories.jpg",
  ],
  [
    "Home & Living",
    "Make your home more comfortable",
    "/src/assets/images/home-living.jpg",
  ],
  [
    "Audio",
    "Headphones and speakers",
    "/src/assets/images/audio.jpg",
  ],
];
const productData = [
  [
    "iPhone 15 Pro",
    "Powerful smartphone with premium camera and display",
    119999,
    "Electronics",
    "/src/assets/images/iphone-15-pro.jpg",
    12,
    1,
    1,
    0,
  ],
  [
    "Samsung Galaxy S24",
    "Flagship Android phone for everyday performance",
    74999,
    "Electronics",
    "/src/assets/images/galaxy-s24.jpg",
    18,
    1,
    1,
    1,
  ],
  [
    "MacBook Air M3",
    "Lightweight laptop for work and development",
    114999,
    "Electronics",
    "/src/assets/images/macbook-air.jpg",
    8,
    1,
    0,
    0,
  ],
  [
    "Gaming Laptop",
    "High performance laptop for gaming and coding",
    89999,
    "Electronics",
    "/src/assets/images/gaming-laptop.jpg",
    6,
    0,
    1,
    1,
  ],
  [
    "Sony Style Wireless Headphones",
    "Comfortable over-ear wireless headphones",
    8999,
    "Audio",
    "/src/assets/images/sony-headphones.jpg",
    30,
    1,
    1,
    0,
  ],
  [
    "Bluetooth Speaker",
    "Portable speaker with deep bass",
    3499,
    "Audio",
    "/src/assets/images/bluetooth-speaker.jpg",
    25,
    0,
    1,
    1,
  ],
  [
    "Men Classic T-Shirt",
    "Soft cotton casual t-shirt",
    999,
    "Fashion",
    "/src/assets/images/tshirt.jpg",
    50,
    1,
    0,
    0,
  ],
  [
    "Denim Jacket",
    "Classic denim jacket for everyday style",
    2499,
    "Fashion",
    "/src/assets/images/denim-jacket.jpg",
    22,
    0,
    1,
    1,
  ],
  [
    "Women Casual Dress",
    "Comfortable and stylish casual dress",
    1999,
    "Fashion",
    "/src/assets/images/casual-dress.jpg",
    28,
    1,
    1,
    0,
  ],
  [
    "Running Shoes",
    "Lightweight shoes for running and walking",
    3999,
    "Footwear",
    "/src/assets/images/running-shoes.jpg",
    35,
    1,
    1,
    1,
  ],
  [
    "Classic Sneakers",
    "Comfortable everyday sneakers",
    2999,
    "Footwear",
    "/src/assets/images/sneakers.jpg",
    31,
    0,
    1,
    0,
  ],
  [
    "Leather Formal Shoes",
    "Premium formal shoes for office wear",
    4499,
    "Footwear",
    "/src/assets/images/formal-shoes.jpg",
    14,
    0,
    0,
    1,
  ],
  [
    "Smart Watch",
    "Track activity, notifications and daily goals",
    5999,
    "Accessories",
    "/src/assets/images/smartwatch.jpg",
    24,
    1,
    1,
    0,
  ],
  [
    "Analog Watch",
    "Minimal classic watch design",
    2999,
    "Accessories",
    "/src/assets/images/analog-watch.jpg",
    20,
    0,
    1,
    1,
  ],
  [
    "Leather Wallet",
    "Compact wallet with multiple card slots",
    1499,
    "Accessories",
    "/src/assets/images/leather-wallet.jpg",
    40,
    0,
    0,
    0,
  ],
  [
    "Sunglasses",
    "UV protection stylish sunglasses",
    1299,
    "Accessories",
    "/src/assets/images/sunglasses.jpg",
    32,
    0,
    1,
    1,
  ],
  [
    "Modern Table Lamp",
    "Warm lighting for your study or bedroom",
    2299,
    "Home & Living",
    "/src/assets/images/table-lamp.jpg",
    16,
    1,
    0,
    0,
  ],
  [
    "Comfort Cushion",
    "Soft cushion for your sofa and bed",
    899,
    "Home & Living",
    "/src/assets/images/cushion.jpg",
    45,
    0,
    1,
    1,
  ],
  [
    "Coffee Mug Set",
    "Minimal ceramic mugs for your kitchen",
    1199,
    "Home & Living",
    "/src/assets/images/coffee-mug.jpg",
    27,
    0,
    0,
    1,
  ],
  [
    "Desk Organizer",
    "Keep your workspace clean and organized",
    1599,
    "Home & Living",
    "/src/assets/images/desk-organizer.jpg",
    19,
    0,
    1,
    0,
  ],
  [
    "Wireless Earbuds",
    "Compact earbuds with charging case",
    4999,
    "Audio",
    "/src/assets/images/wireless-earbuds.jpg",
    34,
    1,
    1,
    1,
  ],
  [
    "Studio Headphones",
    "Clear sound for music and work",
    6999,
    "Audio",
    "/src/assets/images/studio-headphones.jpg",
    11,
    0,
    0,
    0,
  ],
  [
    "Portable Charger",
    "Fast charging power bank",
    2499,
    "Electronics",
    "/src/assets/images/portable-charger.jpg",
    38,
    0,
    1,
    1,
  ],
  [
    "Mechanical Keyboard",
    "Comfortable keyboard for coding and gaming",
    5499,
    "Electronics",
    "/src/assets/images/mechanical-keyboard.jpg",
    17,
    1,
    0,
    0,
  ],
];
await Product.deleteMany({});
await Category.deleteMany({});
const cats = await Category.insertMany(
  categories.map(([name, description, image]) => ({
    name,
    description,
    image,
  })),
);
const map = Object.fromEntries(cats.map((c) => [c.name, c._id]));
await Product.insertMany(
  productData.map(
    ([
      name,
      description,
      price,
      cat,
      image,
      stock,
      featured,
      trending,
      offer,
    ]) => ({
      name,
      description,
      price,
      discountPrice: offer ? Math.round(price * 0.85) : undefined,
      category: map[cat],
      image,
      stock,
      featured: !!featured,
      trending: !!trending,
      offer: !!offer,
    }),
  ),
);
const password = await bcrypt.hash("Admin@123", 10);
await User.deleteOne({ email: "admin@shopverse.com" });
await User.create({
  name: "Admin",
  email: "admin@shopverse.com",
  password,
  role: "admin",
});
console.log("Seed complete: categories + 24 products + admin");
console.log("Admin: admin@shopverse.com / Admin@123");
process.exit();
